authorName: default
experimentName: ft_epoch_sparity_mil_miladd_toys
trialConcurrency: 5
maxTrialNum: 100000
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python run_mminforec.py --ft_epoch=10 --item_sparsity=90 --lr=0.001 --weight_decay=0 --pred_step=1 --tau=0.1 --data_name=Toys_and_Games --num_hidden_layers=1 --num_attention_heads=1 --attention_probs_dropout_prob=0.5 --hidden_dropout_prob=0.5 --dc_s=1 --dc=1 --num_hidden_layers_gru=1 --mil=4 --loss_fuse_dropout_prob=0.5 --epoch=200 --mem=64
  codeDir: '.'
  gpuNum: 1 #!zkx:一个任务分配在几个GPU上
localConfig:
  useActiveGpu: true
  maxTrialNumPerGpu: 1 #!zkx:一个GPU放几个任务
  gpuIndices: 0,1,2,3,4 #!zkx:可以使用的GPU的index
  